name: Syntax Check for Python 3.12.3

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Check Code Syntax with Python 3.12.3
    runs-on: ubuntu-latest

    container: 
      image: python:3.12.3 # Oficjalny obraz Dockera dla Pythona 3.12.3
      options: --user root

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install pycodestyle

    - name: Run pycodestyle
      run: |
        pycodestyle . --statistics --show-source
